config/routes.rb
Rails.application.routes.draw do
  resources :books
  root :to => 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, :body, presence: true, length: { minimum: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	def new
		@book = Book.new
	end

	def edit
		@book = Book.find(params[:id])
	end

	def index
		@books = Book.all
		@book = Book.new
	end

	def update
		@book = Book.find(params[:id])

		if @book.update(book_params)
			flash[:update] = "Book was successfully update."
			redirect_to @book
		else
			render :edit, status: :unprocessable_entity
		end
	end

	def create
		@books = Book.all
		@book = Book.new(book_params)

		if @book.save
		  flash[:notice] = "Book was successfully created."
		  redirect_to @book
		else
		  render :index, status: :unprocessable_entity
		end
	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy
        flash[:destroy] = "Book was successfully destroyed."
		redirect_to books_path
	end

	def show
		@book = Book.find(params[:id])
	end

	private
	  def book_params
	  	params.require(:book).permit(:title, :body)
	  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= @book.errors.count %>件のエラーが発生したため保存ができませんでした。</h2>
      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title, "Title" %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body, "Body" %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>
<!--  -->
<%= link_to 'Show', book_path %>
<!--  -->
| <%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<% if flash[:destroy] %>
  <p><%= flash[:destroy] %></p>
<% end %>
<h1>Books</h1>
<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
  </tr>

  <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td><%= link_to 'Show', book %></td>
      <td><%= link_to 'Edit', edit_book_path(book) %></td>
      <td><%= link_to 'Destroy', book_path(book),
        method: :delete, data: { confirm: '削除しますか?' } %></td>
    </tr>
  <% end %>
</table>

<h2>New book</h2>
<%= render 'form' %>

app/views/books/new.html.erb
<h1>新しい投稿</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<% if flash[:update] %>
  <p><%= flash[:update] %></p>
<% end %>

<p>
  <strong>タイトル：</strong>
  <%= @book.title %>
</p>

<p>
  <strong>内容：</strong>
  <%= @book.body %>
</p>

<%= link_to 'Back', books_path %>
| <%= link_to 'Edit', edit_book_path(@book) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h2>ようこそ、Bookersへ！</h2>

<p>Bookers では、さまざまな書籍に関するあなたの意見や

印象を共有し交換することができます</p>
<%= link_to "start", controller: "books" %>